"""Render the canonical migration list as generated Markdown."""

from pathlib import Path

from aws_connect.infrastructure.sqlite_profile_store import MIGRATIONS


def render() -> str:
    sections = [
        "<!-- Generated by scripts/generate-docs.ps1; do not edit manually. -->",
        "# SQLite Schema",
        "",
        "The following SQL is generated from the ordered migration source.",
    ]
    for version, sql in MIGRATIONS:
        sections.extend(("", f"## Migration {version}", "", "```sql", sql.strip(), "```"))
    return "\n".join(sections) + "\n"


def main(output_path: str) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    import sys

    main(sys.argv[1])
